0xcf/decal-web

- _data/materials.yaml
- _includes/calendar.html
This should work, but if anyone wants to look it over to make sure there aren't any new bugs feel free to.
> Make lab links go to material id

- labs/b2.md
Added https:// to the front, otherwise markdown thinks it's a local link within the directory
> Fixed checkoff link

- _data/materials.yaml
- labs/a7.md
This is essentially the same as b7, but it has an extra section that covers load balancing with haproxy. Using a script from decal-labs (https://github.com/0xcf/decal-labs/pull/8) that starts up a number of workers, these workers can then be put into the haproxy config and have health checks added for each of them to show that haproxy can route around impaired instances, etc.
Ideally I think this lab would be completely different from b7 to allow people who have taken the basic/beginner track in the past to take the advanced one later and not have a bunch of overlapping material, but I think that's something to worry more about in future iterations. Thoughts?
> Add lab a7

- _includes/footer.html
This commit gets rid of the `<div class="row">` in the footer, which was causing the website to horizontally scroll. It shifts the indentation down which makes this look a lot bigger than it really is.
If there's a reason for why we had this in the first place, let me know, otherwise I'll push this within the next few days.
ＦＲＯＮＴ-ＥＮＤ ＷＥＢ ＤＥＶＥＬＯＰＭＥＮＴ
> Fix horizontal scrolling issue

- Jenkinsfile
This checks that whoever makes a PR is a member of the 0xcf organization (or it prompts for approval to run). This could be a little bit annoying, but I think there's a pretty large security benefit to it overall if we can secure all the repos.
> Add check gh trust step

- Jenkinsfile
This redirects alerts for build failures to `decal+jenkins@ocf.berkeley.edu` and messages in IRC to `#decal-spam` from the default of `#rebuild-spam`.
> Use the decal email and channel for Jenkins alerts

- _layouts/home.html
- _sections/intro.md
Add a quick link to the policies in the navbar, and add a box at the top of the page with info about the infosessions
> make info clearer

- labs/a3.md
Resolves #183 
Changes
- Update mirrors and Arch Wiki links
- Partitioning section: add device naming convention, Gradescope question, correct "parition" typos
- Mounting section: add mount explanation, Gradescope question
This is a relatively small update to cooperc's Arch install lab; I initially wanted to reduce the instructions and make it more self-guided but I realized there's quite a lot of stuff that can go wrong and make the lab frustrating if it was less structured. I've added some explanations and Gradescope questions to test understanding at points where they felt relevant. I edited this lab without actually doing an Arch install while going through it, so we should probably do a run through on an actual DO droplet to see if there are any parts that people might have trouble …
> Update lab a3

- _includes/interestform.html
Seems like people using Firefox or Brave have been experiencing some unpredictability with the Google form embed. While we work on making sure it works for everyone, here's a quick link in case it's broken.
> Add interest form redirect notice

- labs/b9.md
- Rewrote the Git exercise to be more detailed and use a Python example program instead of C.
- Added an exercise to make a dummy PR on Github. The dummy repo still needs to be set up and the lab instructions updated with the repo URL for this semester.
Related PR to update the lab b9 example code: https://github.com/0xcf/decal-labs/pull/21
> Update lab b9

- labs/a3.md
Some instructions are slightly broken since the lab was initially written. Should've done a run-through beforehand, my bad.
---
Fix installation media and VM setup instructions
- Add note to try OCF keyserver if gpg command fails
- Bold warning at the beginning of Create VM section
- Increase virt-install memory flag to 704MB
> Lab a3 Fixes

- labs/a3.md
Some people were having issues during lab a3 where executing the commands in the Create Filesystems --> Wiping section would cause the Arch VM to reboot into the UEFI shell. According to people troubleshooting on Slack, this issue was resolved by following the DO droplet's motd prompting the user to upgrade packages and reboot the droplet. Not sure why this behavior manifests, as I don't think using older packages should have affected the lab. I've added a note at the top of the lab to upgrade and reboot before attempting the lab.
> Add warning to upgrade/reboot DO droplet

- labs/a4.md
- fix link to selinuxproject.org, otherwise it jumps to https://decal.ocf.berkeley.edu/labs/selinunxproject.org
- change http links to https
> Lab a4 link fix

- labs/a6.md
This problem had a major issue in its original instructions because running the provided scripts broke networking on the student vm's, making them inaccessible via ssh.
I've tested these instructions to be working (login to `staff4` if you want to try for yourself).
Don't push these changes until the corresponding PR in decal-labs has gone through. (https://github.com/0xcf/decal-labs/pull/23)
> Rewrite a6 "this is fine" problem

- labs/a7.md
- change /opt/lab7/readonly,readwrite to mnt
- Piazza delete
- DNS: instruct students to intentionally bring down bind9
- Change location of bind9.service to /lib/systemd/system/named.service
- Link to named.conf.local  in decal-labs
- Instructions to install HAProxy
- Install tornado using apt install python3-tornado
> Fixes to a7 spec

- labs/a7.md
In Ubuntu 18.04, `bind9.service` is at `/lib/systemd/system/bind9.service`, but in 20.04, it's at `/lib/systemd/system/named.service`.
See https://packages.ubuntu.com/bionic/amd64/bind9/filelist (18.04LTS) and https://packages.ubuntu.com/focal/amd64/bind9/filelist (20.04LTS) and search for `.service` for the current package content.
The more reliable way of cat that file should be `systemctl cat bind9`. Because on Ubuntu 20.04 `bind9.service` is an alias to `named.service`, it works on both releases.
> a7: fix bind9 systemd unit file info

- labs/a9.md
Should be `q2.txt.gpg` and not `q1.gpg`
> Fix task 2 filename in a9

- Gemfile.lock
- Makefile
For some reason, merging just-the-class into master fails spectacularly. This is an attempted resolution.
> Fix Jenkins (Downgrade bundler, add makefile)

- labs/b1.md
Running `wget` seems to create the error 
```
ERROR: The certificate of ‘decal.ocf.berkeley.edu’ is not trusted.
ERROR: The certificate of ‘decal.ocf.berkeley.edu’ hasn't got a known issuer.
```
This is a workaround for that (while we figure out what's going on).
> Add message about certificate trust issues

- labs/a6.md
For question 3b, there is no `retry:n` in Linux `/etc/resolv.conf`. For Solaris, however, there is indeed a `retry:n`: "Sets the number of attempts made to connect to _each_ name server". The Linux counterpart is `attempts:n`, which counts the total queries sent before giving up. See Oracle's manual and Linux Programmer's Manual for exact definitions.
Resolves #281
> Lab a6 updates

- _data/materials.yaml
I put the week 1 answers into a new folder for fall 2021, and shared it with the students based on the gradescope rosters.
> Changed week 1 answer links

- index.md
- staff.md
This is to minimize the number of students who email staff members directly. Adding this all to the front page might be extreme, but it allows users to read the page top-to-bottom to get all the information they need. This is especially helpful on mobile.
> add communication info to front page

- Makefile
Same as PR #373 but with support for git versions older than 2.22
> Fix getting branch for git < 2.22

- labs/a3.md
Since we have Ubuntu 20 VM, libvirt-bin cannot be installed in this version. See [this](https://askubuntu.com/a/1089849) for more info
> Update libvirt-bin for Ubuntu 20

- labs/b4.md
From Piazza:
> The ruby version newly installed is 2.7.0, while the command in lab instruction says "to add ~/.gem/ruby/2.5.0/bin to your PATH (list of directories to find executables)" is outdated. So, the command should be ~/.gem/ruby/2.7.0/bin to allow fpm to be executable in bash. 
This PR removes the version number from the instructions, instead directing readers to check `ruby --version`.
> b4: remove ruby version number

- _layouts/default.html
- _layouts/lab.html
- _layouts/staffer.html
- labs/11.md
- labs/a1.md
- labs/a10.md
- labs/a2.md
- labs/a3.md
- labs/a4.md
- labs/a5.md
- labs/a6.md
- labs/a7.md
- labs/a8.md
- labs/a9.md
- labs/b1.md
- labs/b10.md
- labs/b2.md
- labs/b3.md
- labs/b4.md
- labs/b5.md
- labs/b6.md
- labs/b7.md
- labs/b8.md
- labs/b9.md
Adds a facilitator title to each lab using facilitator list from the Google Doc. If there isn't a slot in the spreadsheet, the facilitator is ignored. There were also some facilitators I didn't know which profile to put for them, so I left blank.
Each lab markdown has a new `facilitator` property. It should be their name in their associated `_staffer` markdown file:
```md
---
title: Lab a1 - Shell Scripting
layout: lab
facilitator: Ben Cuan
nav_exclude: true
---
...
```
If no facilitator, it is null:
```md
---
title: Lab 6 - Processes and Services
layout: lab
facilitator: null
nav_exclude: true
---
...
```
Example:
Clicking on the link will take the viewer to the staff page at the location of the staffer with a spotlight effect around them:
If no facilitator found, page will appear as …
> Add lab contact info

- labs/11.md
Basic lab struggled with erb vs puppet syntax since the difference wasn't made clear
> Add ERB Hint for lab 11

- labs/s2.md
The links to OCF docs used a relative link so it wouldn't hyperlink properly :(
> Fix docs relative links

- labs/s3.md
There were brackets instead of parentheses around rt.ocf.io.
> Fix Request Tracker (RT)
