0xcf/decal-web

- _data/calendar.yaml
- _data/materials.yaml
- labs/5.md
> Adding materials for lecture/lab 5 of the sysadmin decal

- labs/5.md
Line breaks and a hint for the tcpdump command.
> Some Quality of Life Changes to the lab document

- Jenkinsfile
Fixes #4, though it's possible I messed up the syntax.
> Disable concurrent Jenkins builds

- LICENSE
seems appropriate considering that the decal materials are generally non-code assets and can hopefully be reused by others looking to teach similar courses
> relicense from MIT to CC-BY-SA 4.0

- _data/calendar.yaml
- _data/materials.yaml
> add slides for lectures 9 and 10

- .gitignore
- Makefile
- README.md
So no one else has to google it.
> Install instructions

- _includes/staff.html
Simple fix for the annoying imperfect grid wrapping
> Fix staff grid wrapping

- _data/staff.yaml
> remove ldw as facilitator since he gone

- _layouts/home.html
so it's clear people need to do lab0
> remove interest form

- Jenkinsfile
this should (?) work if we change DNS for decal.ocf.* from death to lowgpa, I've added the jenkins decal deploy key to ocfdecal@lowgpa:.ssh/authorized_keys
> Change Jenkinsfile deploy target

- labs/b2.md
> Remove duplicated content

- _data/beginner_calendar.yaml
forgot to update calendar in my last pr whoops
> added b3 info to beginner_calendar.yaml, which I forgot to do before

- labs/a4.md
Very rough draft, I'll clean this up soon and do more testing but if anyone has comments feel free to add.
> Lab a4 draft

- _data/materials.yaml
- labs/a5.md
> adding lab a5

- _data/advanced_calendar.yaml
- _data/materials.yaml
We'll merge this sometime before lecture tomorrow, just seemed like a good idea to stage it ready for then so it's easy to one-click deploy.
> Add slides for a9

- _data/materials.yaml
- labs/a8.md
much of this is the same from last semester, and I was adding material to the end 2 weeks ago, but need to continue to add stuff.
> lab a8 draft

- _config.yml
- _includes/interestform.html
- _layouts/home.html
https://docs.google.com/forms/d/1P3PL3KfhsY9L7P0LWTzJJHFJ_pLRJvTzdk5KqIuD5XM/edit
is the form itself
> add fall 2018 interest form

- Jenkinsfile
- Makefile
> declarative jenkinsfile @ decal

- labs/a1.md
I decided to make this extremely simple compared to the previous lab A1. All of the solutions are less than 5 lines of code, but they explore things like for loops, shell expansion, wildcards and such. Of course, all the solutions can be implemented in many different ways. My solutions are in the Advanced 1 Drive folder.
> add fa18 lab a1

- _data/advanced_calendar.yaml
- _data/beginner_calendar.yaml
- _includes/calendar.html
This makes the due dates of labs more clear.
> Add lab due dates to calendar

- _data/beginner_calendar.yaml
- _data/materials.yaml
Also push the due date back a week.
> Add B4 lab link

- _data/beginner_calendar.yaml
- _data/materials.yaml
This is for my lecture this evening!
> Add b7 lecture slides

- _data/advanced_calendar.yaml
- _data/materials.yaml
- labs/a5.md
lab a5 was described previously as being too long, and I don't currently have the bandwidth to test the lab and grade the results. I've made it optional for students to complete. The document itself should serve as a good reference, however.
> add topic guide a5, calendar updates

- _data/materials.yaml
- labs/b8.md
People'll need to have imported b8/privkey in the "Encryption/Decryption"  section before moving onto the "File Security" section and running setup.sh.
> Update lab b8 to reflect new setup.sh

- _data/materials.yaml
- _includes/calendar.html
so we can more easily give credit to the many guest lecturers who have graced us with their presence this semester
> add key to list who gave which lecture

- _data/materials.yaml
this points to a Fall 2019 infosession slide deck that's in the Fall 2019 folder
> materials: Update infosession slide link

- _data/advanced_calendar.yaml
- _data/materials.yaml
> Fix advanced lecture calendar

- _data/beginner_calendar.yaml
- labs/b1.md
> fixes for lab b1

- labs/a1.md
i merged too soon like a clown
> Implementing suggestions

- _includes/head.html
This is necessary for the navbar to work on mobile.
> add Bootstrap JS

- labs/b1.md
I tried for 15 minutes and couldn't figure out how to get the max column number down
> Add xkcd title text for lab b1

- _data/beginner_calendar.yaml
- _data/materials.yaml
- labs/b3.md
Holy crap whoever did this lab prior did a ton of work on this. The lab itself practically has a lecture in it!
> B3 Content

- _data/beginner_calendar.yaml
- _data/materials.yaml
- labs/b4.md
Basically copypasta'd from last years. Found a missing word which I fixed, and said go to gradescope instead of the google forms.
> Add lab b4

- labs/a4.md
Found another missing word. Proofreading works!
> Add lab a4

- _data/advanced_calendar.yaml
> Add labdue for a4

- _data/materials.yaml
> add b10 slides

- labs/b10.md
it's pretty much the lab from past semesters with a few updates
> add lab b10

- labs/a1.md
Some notes:
- Moved Q1 to Q4. Will need to set Bernard's question as Q1 (#175)
- For the getting help section, might consider adding something about going into lab to talk to us (contingent on whether or not lab will be open).
- Add due date or some information about lab due dates in general when we finalize those.
> Update existing lab a1 questions/content

- Gemfile.lock
- labs/a1.md
Not sure if the Gemfile version bump will destroy anything.
As for the actual question, I think it might actually be too easy compared to the rest of the questions. Do you guys have a better idea of what to do than just run mkdir? I think it wouldn't be crazy to chain one more command here.
> New question for lab a1

- labs/a4.md
Resolves #181.
Some changes:
- Fixed some minor formatting stuff.
- Added all of the Gradescope questions from fa9 + added a couple more.
- Fixed broken CherryMusic link
- Improved some wording of things
> Update lab a4

- labs/b1.md
> Update lab b1

- labs/a5.md
- labs/a6.md
Resolves #194.
This lab was pretty good so I didn't make very many changes. 
I mostly just made the questions clearer and fixed a couple formatting issues here and there.
(This was previously lab a6 in fa2019.)
> Update lab a5

- labs/b7.md
Completes #187. Don't think a ton of changes are necessary here, as in the point of getting people acquainted with systemd is well accomplished by this lab.
> Lab b7 updates

- _sections/intro.md
Wording likely needs to be updated.
> Add outdated notice to DeCal website

- _data/advanced_calendar.yaml
- _data/beginner_calendar.yaml
- _data/materials.yaml
- _includes/calendar-table.html
- _layouts/home.html
Some changes:
- Update links for syllabus and lab 0
- Change dates to fa20
- Hide links for labs and lectures that have not yet been completed
- Reset lab due dates and lecturers
> Update calendar for fa20

- _includes/interestform.html
- _layouts/home.html
- _sections/intro.md
- _sections/policies.md
Updated policies for fa20. Also, I added a new FAQ section below the existing policies section to address some of the questions that people seem to be asking. (Please let me know if anything needs to be added/changed there since it's new.) 
Some things that still need to be addressed:
- How will we be delivering lectures? (Zoom? Twitch? Prerecorded lectures?)
- Add a link to the interest form when we release it
> Update administrivia for fa20 (+ add FAQ)

- labs/a6.md
Resolves #180
This lab's a big one!
To see what changes I made, don't rely on the 'review changes' panel since this file was re-added. Instead, go to [this commit link](https://github.com/0xcf/decal-web/commit/7501190be3b66b655c1f69df56b605649e67e438).
**A non-exhaustive changelog:**
- Renamed from a5 to a6
- Removed section about setting up a VM (since they're already getting some from DO)
- Distribute conceptual questions with their corresponding sections rather than all at the end (massive blocks of text with no breaks can get intimidating!)
- Added an additional question (1b) to ease into the harder questions
- Fix some random minor typos/grammatical tweaks to make things hopefully a little more concise
**Things that need to be done at a future date:**
- Run through the lab, …
> Update lab a6 (from sp18)

- labs/b4.md
> Update lab b4

- labs/a7.md
Should resolve #193 
Didn't look at this too carefully- will add more updates later. Just wanted to get this out there.
One thing to note- this lab seems to require us to set up a NFS server for people to connect to, so we'll need to do a little extra work to get that setup.
> Add lab a7

- labs/a1.md
- labs/a10.md
- labs/a2.md
- labs/a3.md
- labs/a4.md
- labs/a5.md
- labs/a6.md
- labs/a7.md
- labs/a8.md
- labs/a9.md
- labs/b1.md
- labs/b10.md
- labs/b2.md
- labs/b3.md
- labs/b4.md
- labs/b5.md
- labs/b6.md
- labs/b7.md
- labs/b8.md
- labs/b9.md
Adds a simple table of contents onto each lab page.
No fixed sidebar yet.
> [feature] Add table of contents

- labs/b6.md
> Some prelim updates to b6

- labs/b10.md
This lab looks good. This is one of those labs without much text introduction, so the only thing that I was thinking about adding was adding some information about _why_ Puppet and Docker are useful, which I think the advanced labs do much better. Fixes #182
> Small lab 10 updates

- labs/a10.md
This should finish up the first round of updates for the advanced track!
Not too many changes here; a10 was a pretty solid lab. Here's a summary of the changes:
- Hide legacy Google form. The questions will be on Gradescope this semester.
- Streamline question wording/formatting.
> Update lab a10

- _data/materials.yaml
> Update infosession slide link

- _data/staff.yaml
enslaved silicon old meme
going to instamerge this since it's a one string change
> update my bio for fa20

- .htaccess
- _data/advanced_calendar.yaml
- _data/beginner_calendar.yaml
- _data/materials.yaml
- _includes/calendar-table.html
- _layouts/home.html
- _sections/announcements.md
**DO NOT MERGE UNTIL SUNDAY**
Some link/site content updates for week 1:
- Update /syllabus to fa20
- Add video data
- Add additional slides link to table. Lecture title now links to videos by default.
- Add lecturers for first 4 weeks
- Unhide b1/a1 links from homepage
- Make more announcements
> Week 1 content update

- _data/advanced_calendar.yaml
- _data/beginner_calendar.yaml
- _data/materials.yaml
- _includes/calendar-table.html
- _sections/announcements.md
Don't merge until this weekend ish.
Some changes:
- Unlocked b2 and a2
- Announcements
- Fixed bug in slides link (check for existence of slides not video)
- Fill out lecturer schedule
> Week 2 updates

- _data/materials.yaml
Going to automerge this one in since all it's changing is a video link (plus gotta fix this fast for students).
> Fix b2 video link

- labs/b1.md
This was a point of confusion for a student. "head" isn't mentioned anywhere on the page, so give it a bit of background.
> Reword question about head command

- _data/advanced_calendar.yaml
- _data/materials.yaml
- _sections/announcements.md
- _sections/policies.md
- Edited announcements
- Fixed Tony's ocf username
- Add week 3 content
- Update faq to reflect sp21 status
> Week 3 Content Updates

- _data/advanced_calendar.yaml
- _data/beginner_calendar.yaml
- _data/materials.yaml
- _sections/announcements.md
Changed announcements, added videos and slides. Nothing special this week :)
> Week 4 updates

- _sections/announcements.md
oops i got rid of it :( 
will be automerging this cuz people need it fast
> Add back zoom link

- labs/a4.md
> Remove references to external firewall in a4

- _data/materials.yaml
> Add contents for b5

- _data/advanced_calendar.yaml
- _data/materials.yaml
- labs/a5.md
> update lab for a5

- _data/beginner_calendar.yaml
- _data/materials.yaml
- _sections/announcements.md
- _sections/policies.md
b5 updates were pushed in #247, and a5 updates were pushed in #250. a5 video is coming soon!
This PR includes:
- Updated announcements for week 5
- Add due date for b5
- Add discord link on homepage
- Add extra FAQ about enrollment (getting ready for sp21)
> Week 5 updates

- _data/materials.yaml
- _sections/announcements.md
Some notes:
- Announcements are pretty much unchanged other than the lab/lecture numbers
- a6 video OR live lecture notification still pending (but lab has been unlocked)
- b6 updates in #253
> Week 6 Updates

- _data/materials.yaml
link to lecture recording: https://drive.google.com/file/d/1bwfhukWjvLw8IsgOhG46XqM9uIbz6yX1/view?usp=sharing
> [decal/a6] update slide link to FA2020 version

- labs/a6.md
Instructions to use vagrant should be added back since these scripts will remove network connectivity if run on a student VM
> Comment out this is fire section

- labs/a7.md
Based off of @jvperrin's comments in #264. Thanks for the thorough review! (go to #264 to see what issues this fixes)
> More fixes to a7 spec

- _data/materials.yaml
- labs/a8.md
Changes:
- Lab reuses the one from sp18. There are a couple of issues with the newer one incl. system requirements
- miscellaneous bugfixes and updates
> a8 fa20 updates

- _data/materials.yaml
- _sections/announcements.md
a9 isn't released just yet, so I held off on releasing those materials for now. We can make them public when things get fixed up.
> Add a8 video + week 9 announcements

- _sections/announcements.md
The late due date was incorrect. Changed dec 11 -> 15
> Fix announcements

- _announcements/week-0.md
- _config.yml
> Fix email in announcements, fix doubleslash in redirect url

- labs/a1.md
Resolves #301 
Feedback for this lab was positive, so there's not too much to change. Some highlights:
- Q3 was reportedly easier than Q2, so I switched them around.
- Added some more general notes to explain labs since this is the first one
- Added some more specific instructions
> Update Lab a1 for sp21 (resolves #301)

- labs/a2.md
Resolves #300 
The main feedback for this lab was that it's too easy, so I added an extra question. Feedback appreciated!
> Update lab a2 for sp21 (Resolves #300)

- labs/a3.md
Resolves #299.
Based on feedback, students tended to fall in one of two groups: either this went great and they really enjoyed it, or they ran into some obscure issue and banged their heads into the keyboard for 6+ hours.
We ideally want everyone to be in the former group, so I've written some very clear instructions at the top and gave some additional leeway should things go sideways.
> Update lab a3 for sp21

- labs/a4.md
Resolves #298.
The main issue was that students were unsure where to do this lab (since they just installed a nested archvm in the previous lab) so I added some clarification.
There are also some reports of the suggested services not working properly (notably cherrymusic and fluffy). I tried installing fluffy with no success (error on `make venv`) so this probably needs further investigation
> Update lab a4 for sp21

- labs/b1.md
See #291 for more details / changes.
> b1 fixes for sp21

- labs/b2.md
See #290 for more details. I ended up adding the requested information about regex/sed to the next lab.
> Update b2 for sp21

- labs/b3.md
> Update b3 for sp21

- labs/b4.md
See #288 for more details.
I added a more guided version of the spelunking question that will be added to a2 as well. Hopefully this will make the lab more insightful since a lot of people thought it was too easy.
> update b4 for sp21

- _staffers/ethanhs.md
> Needs more jpg

- _announcements/week-0.md
- about.md
Going to auto merge this one because this info is needed before I send out emails in a moment, and it's just administrivia (so no actual content or code-related changes). If you see anything that needs fixing we can update it afterwards.
> Update admistrivia for sp21

- _announcements/week-3.md
- _data/materials.yaml
- index.md
- labs/a3.md
- labs/b3.md
- Add announcements
- Add support for solution links in schedule
- Fix formatting in a3
- Fix bug in b3 example
- Add extra lab info in b3
> Week 3 updates (sp21)

- labs/b3.md
Also see https://github.com/0xcf/decal-labs/pull/30
> Add clarification on lookup (b3)

- labs/a3.md
- labs/b3.md
See commit message for more details.
> a3 Fixes and network clarification

- labs/a3.md
> remove formatting section (alternative version)

- _announcements/week-7.md
- _data/materials.yaml
- index.md
- labs/a7.md
- labs/b8.md
- Some routine announcements and frontpage updates.
- Add solutions to labs 4 and 5
- Add hints to part 3 of a7 (past feedback indicated that not enough direction was given for this part)
- Fix b8 title to not say fall 2020
> Week 7 Updates (sp21)

- _announcements/week-8.md
- _data/materials.yaml
- labs/a8.md
- labs/b8.md
- Small improvements in wording for b8
- Add more hints and info about feedback in a8
- Update announcements etc.
Also see https://github.com/0xcf/decal-labs/pull/31
> Week 8 updates (sp21)

- _announcements/week-9.md
- _data/materials.yaml
- labs/a9.md
- labs/b8.md
- Some routine announcements
- Made a9 significantly less work (everyone was complaining about the workload in the feedback last semester): made letsencrypt optional, and remove file swapping exercises.
- We forgot to collect feedback from the (newly written) b9 last semester, so no changes have been made.
> Week 9 updates

- _announcements/week-10.md
- _data/materials.yaml
- labs/11.md
- labs/a10.md
* Some routine announcements
* Minecraft lab is back! (see /labs/11)
* Release some solutions for labs 6 and 7
> Week 10 updates (sp21)

- _announcements/week-11.md
- _data/materials.yaml
- index.md
- publish lab11
- publish lab8 solutions
- standard announcements for the week
> Week 11 updates

- _layouts/lab.html
- about.md
- labs/a4.md
- labs/b4.md
Resolves #350.
This PR includes:
- Minor changes to a4: Generally super positive feedback for this one, but some past students wanted to see more firewall info and additional examples of things they could install on the server, so I have provided a bit of this.
- Minor changes to b4: One question in the feedback was "where do the package files come from?" so I wrote a small blurb about mirrors.
- Auto dark mode: The lab page now detects the system/browser dark mode setting (if it exists) and automatically starts the page out as dark theme if needed.
- Update FAQ: state that it's likely for this class to come back in fa21.
> a4/b4 updates, auto dark mode

- _announcements/week-0.md
In-person details in Week 0 announcement
> Added in-person info session details to Week 0 announcement

- _announcements/week-0.md
> Week 0 updates

- _announcements/week-1.md
- _config.yml
- _data/materials.yaml
Added piazza and week 1 updates
> Week 1 Updates

- _data/materials.yaml
> Fixed Solutions

- labs/a3.md
Just to make it quicker for this semester's lab, I updated the link for Arch's latest release.
> Update last Arch version in A3 course

- _announcements/week-3.md
- _data/materials.yaml
- about.md
I didn't add office hours to the weekly schedule since the SCSS file controlling it doesn't properly space out the event boxes
> Week 3 announcements done

- Makefile
- test
Testing if the branch var will work as expected with Jenkins
> Adding a branch var to Makefile

- labs/a3.md
Updates to A3 for Ubuntu 20.04
Hosted for the moment at : http://supernova.ocf.berkeley.edu:8595//
> Update a3 lab

- Jenkinsfile
- Makefile
Currently testing things, the final goal is to get PR's to trigger a build to `public_html/pr/<PR_NUMBER>` and have Jenkins send a link to it so we can have automated deploy previews for PR's.
> Enable branch pr's

- Jenkinsfile
Jenkins will send a message to #decal-comm every time there's a PR to this repo.
> Get PR messages on #decal-comm

- labs/a6.md
Updated vagrant version, added ansible as vagrant depends on it
> Lab a6 fixes

- Gemfile.lock
Security patch for dependencies﻿
> Security Patch

- labs/a9.md
> fixed A9 lab formatting

- about.md
Edit the syllabus to reflect the upcoming semester's policy changes.
> Spring 2022 Policy Updates

- labs/a1.md
Added hints and rearranged questions to make the lab easier and improve flow.
> Added hints to a1

- README.md
Added instructions for development on supernova, which should be easier to get working for all staffers.
> Update Development instructions

- _announcements/week-1.md
- _data/materials.yaml
Added week 1 labs and announcement.
> week 1 labs + announcement

- _announcements/week-1.md
> changes to week 1 annouc

- _staffers/lance.md
- labs/a1.md
- labs/a10.md
- labs/a2.md
- labs/a5.md
- labs/a6.md
- labs/a7.md
- labs/a8.md
- labs/a9.md
- labs/b1.md
- labs/b10.md
- labs/b2.md
- labs/b4.md
- labs/b5.md
- labs/b6.md
- labs/b7.md
- labs/b8.md
- labs/b9.md
Changed facilitators for each lab
> Lab update

- _announcements/week-2.md
- _data/materials.yaml
Released week 2 labs and announcement
> released week 2 lab and announcement

- _announcements/week-4.md
- _data/materials.yaml
Week 4 announcement  + lab 1 solutions
> week 4 announcement + lab1 solutions

- labs/s3.md
The link was broken; remove the "minutes."
> Fix ocf.io/bod/minutes

- _announcements/week-0.md
- _data/materials.yaml
- _schedules/weekly.md
- index.md
- reconfigure for spring 2023 (remove beg/adv track)
- add week 0 announcement
- add infosession dates
> Spring 2023 Week 0

- _announcements/week-1.md
- _data/materials.yaml
- labs/1.md
Updates the website to include an announcement for week 1 and opens public access to lab1. Someone please check to make sure the announcement contains accurate information.
> Fa23 week1 updates

- index.md
Fixes an issue where recording and slides links would show up, even if not provided.
> fix display recording and slides

- _announcements/week-1.md
- _staffers/owent.md
> Add information about joining Ed and Gradescope
